Addr:                "localhost:21",
User:                "yusufcan",
Password:            "Banana@@",
NetworkToUploadPath: "/home/yusufcan/Desktop/network_toupload",
NetworkOutgoingPath: "/home/yusufcan/Desktop/network_outgoing",
NetworkIncomingPath: "/home/yusufcan/Desktop/network_incoming",
FTPWritePath:        "/home/yusufcan/Desktop/ftp_write",
FTPReadPath:         "/home/yusufcan/Desktop/ftp_read",
PoolInterval:        time.Second * 5,
HeartBeatInterval:   time.Second * 1,
LogFilePath:
LogLevel: -4
LokiPushURl:
