addr:                localhost:21
user:                yusufcan
password:            Banana@@
networkBasePath:     /home/yusufcan/Desktop/base
networkToUploadPath: /Gidecek
networkOutgoingPath: /Giden
networkIncomingPath: /Gelen
ftpWritePath:        /home/yusufcan/Desktop/ftp_write
ftpReadPath:         /home/yusufcan/Desktop/ftp_read
poolInterval:        5s
heartbeatInterval:   1s
logFilePath: ./log.txt
logLevel: -4
lokiPushURl: http://localhost:3100/loki/api/v1/push
